config/routes.rb
Censusview::Application.routes.draw do

  get "census_vars" => 'census_vars#index'

  get "site/index"

  resources :census_counts

  match "/" => redirect("/census_counts/totpop")

end

app/models/census_var.rb
class CensusVar < ActiveRecord::Base
  attr_accessible :longlabel, :units, :variableid, :varlabel, :vartype
  attr_accessor :tokens
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/census_counts_controller.rb
class CensusCountsController < ApplicationController
  # GET /census_counts
  # GET /census_counts.json
  def index
    @census_counts = CensusCount.all

    respond_to do |format|
      format.json
    end
  end

  # GET /census_counts/TotPop.json
  def show
    # @census_count = CensusCount.find(params[:id])
    # @census_counts = CensusCount.all
    @census_counts = CensusCount.select([:postarea, params[:id]]).all

    @census_var = params[:id]
    # @test = CensusCount.pluck(:id)

    # @census_var = params[:id]

    respond_to do |format|
      format.json
      format.html
    end
  end

  # GET /census_counts/new
  # GET /census_counts/new.json
  def new
    @census_count = CensusCount.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @census_count }
    end
  end

  # GET /census_counts/1/edit
  def edit
    @census_count = CensusCount.find(params[:id])
  end

  # POST /census_counts
  # POST /census_counts.json
  def create
    @census_count = CensusCount.new(params[:census_count])

    respond_to do |format|
      if @census_count.save
        format.html { redirect_to @census_count, notice: 'Census count was successfully created.' }
        format.json { render json: @census_count, status: :created, location: @census_count }
      else
        format.html { render action: "new" }
        format.json { render json: @census_count.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /census_counts/1
  # PUT /census_counts/1.json
  def update
    @census_count = CensusCount.find(params[:id])

    respond_to do |format|
      if @census_count.update_attributes(params[:census_count])
        format.html { redirect_to @census_count, notice: 'Census count was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @census_count.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /census_counts/1
  # DELETE /census_counts/1.json
  def destroy
    @census_count = CensusCount.find(params[:id])
    @census_count.destroy

    respond_to do |format|
      format.html { redirect_to census_counts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/census_vars_controller.rb
class CensusVarsController < ApplicationController
  # GET /census_vars
  # GET /census_vars.json
  def index
    @census_vars = CensusVar.all
    @longlabels = CensusVar.select(:longlabel)

    # Tokenization. Removing this - should be done automatically by Twitter Typahead
    # @census_vars.each_with_index do |census_var, i|
    # 	census_var.tokens = census_var.longlabel.to_s.split(' ')
    # 	census_var.tokens.append @census_vars[i][:varlabel]
    # 	census_var.tokens.append 'all'
    # end

    respond_to do |format|
      format.json
    end
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/census_counts_helper.rb
module CensusCountsHelper
end

app/helpers/census_vars_helper.rb
module CensusVarsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/census_counts/_form.html.erb
<%= form_for(@census_count) do |f| %>
  <% if @census_count.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@census_count.errors.count, "error") %> prohibited this census_count from being saved:</h2>

      <ul>
      <% @census_count.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :area_id %><br />
    <%= f.text_field :area_id %>
  </div>
  <div class="field">
    <%= f.label :male %><br />
    <%= f.number_field :male %>
  </div>
  <div class="field">
    <%= f.label :female %><br />
    <%= f.number_field :female %>
  </div>
  <div class="field">
    <%= f.label :totpop %><br />
    <%= f.number_field :totpop %>
  </div>
  <div class="field">
    <%= f.label :tot16to74 %><br />
    <%= f.number_field :tot16to74 %>
  </div>
  <div class="field">
    <%= f.label :totadult %><br />
    <%= f.number_field :totadult %>
  </div>
  <div class="field">
    <%= f.label :totemploy %><br />
    <%= f.number_field :totemploy %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/census_counts/edit.html.erb
<h1>Editing census_count</h1>

<%= render 'form' %>

<%= link_to 'Show', @census_count %> |
<%= link_to 'Back', census_counts_path %>

app/views/census_counts/index.html.erb
<h1>Listing census_counts</h1>

<table>
  <tr>
    <th>Area</th>
    <th>Male</th>
    <th>Female</th>
    <th>Totpop</th>
    <th>Tot16to74</th>
    <th>Totadult</th>
    <th>Totemploy</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @census_counts.each do |census_count| %>
  <tr>
    <td><%= census_count.area_id %></td>
    <td><%= census_count.male %></td>
    <td><%= census_count.female %></td>
    <td><%= census_count.totpop %></td>
    <td><%= census_count.tot16to74 %></td>
    <td><%= census_count.totadult %></td>
    <td><%= census_count.totemploy %></td>
    <td><%= link_to 'Show', census_count %></td>
    <td><%= link_to 'Edit', edit_census_count_path(census_count) %></td>
    <td><%= link_to 'Destroy', census_count, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Census count', new_census_count_path %>

app/views/census_counts/new.html.erb
<h1>New census_count</h1>

<%= render 'form' %>

<%= link_to 'Back', census_counts_path %>

app/views/census_counts/show.html.erb
<div id="map"></div>

app/views/census_vars/index.html.erb
<h1>CensusVars#index</h1>
<p>Find me in app/views/census_vars/index.html.erb</p>

app/views/layouts/_body.html.erb
<div class="small-8 columns">
    <%= yield %>
</div>
<div class="small-4 columns" id='sidebar'>
	<div></div>
</div>

app/views/layouts/_footer.html.erb
<footer class="small-12 columns">
	<h6 class='subheader'>
       by <a href="https://github.com/samuelleach/censusview">Samuel Leach</a>, with inspiration
       from the <a href="http://bl.ocks.org/mbostock/5562380">examples</a> of Mike Bostock.
       <a href="http://geolytix.co.uk/geodata/postal-boundaries">Map shapefiles</a>
       (processed with <a href="http://www.gdal.org">ogr2ogr</a> and <a href="https://github.com/samuelleach/uk-atlas">compressed</a> with topojson) and
       <a href="http://geolytix.co.uk/geodata/census">2011 Census data</a> via Geolytix,
       <a href="https://github.com/samuelleach/uk-census">reprocessed with python</a> using
       <a href="http://www.ons.gov.uk/ons/guide-method/geography/products/census/lookup/other/index.html">
       postcode to Census Output Area look-up files</a> from the Office of National Statistics.
       Polygon areas calculated using <a href="http://www.qgis.org/">QGIS</a>.
       Data rendered with <a href="http://d3js.org">D3</a>.
       Colors by <a href="http://colorbrewer2.org">Colorbrewer</a>. Search with <a href="http://twitter.github.io/typeahead.js/">typeahead</a>. Styling with <a href="http://foundation.zurb.com">Foundation</a>.
       Created at <a href="https://generalassemb.ly/london">General Assembly, London</a> (June 2013)
</footer>

app/views/layouts/_header.html.erb
<header class="small-12 columns">
	<div class='left'>
		<h2>CensusView</h2>
	</div>
	<div class='right'>
		<h4>Where do they live?</h4>
		<p><%= @census_var %> population<p>
	</div>
</header>

app/views/layouts/_share.html.erb
<div id='share' class="small-12 columns">
	<div class='right'>
	<a href="https://twitter.com/SamuelLeach" class="twitter-follow-button" data-show-count="false">
		Follow @SamuelLeach
	</a>
	<script>
		!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
	</script>
	</div>
</div>

app/views/layouts/_typeahead.html.erb
<div class="large-12 columns">
	<input class="typeahead" placeholder="eg: totpop, ethnic, marital status, economic activity, health, all"></input>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "CensusView" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body data-census_var="<%= @census_var %>">

    <div class="container">
      <div class='row'><%= render :partial => 'layouts/header' %></div>
      <div class='row'><%= render :partial => 'layouts/typeahead' %></div>
      <div class='row'><%= render :partial => 'layouts/body' %></div>
      <div class='row'><%= render :partial => 'layouts/footer' %></div>
      <div class='row'><%= render :partial => 'layouts/share' %></div>
    </div>

    <script src="/js/d3.v3.min.js"></script>
    <script src="/js/topojson.v1.min.js"></script>
    <script src="/js/crossfilter.min.js"></script>
    <script src="/js/queue.v1.min.js"></script>
    <script src="/js/colorbrewer.js"></script>
    <%= javascript_include_tag "application" %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-41789569-1', 'herokuapp.com');
      ga('send', 'pageview');
    </script>
  </body>
</html>